apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define the base manifests (YAML files)
resources:
  - nginx-deployment.yaml

# Apply common labels
#commonLabels:
#  app: my-app

# Set environment variables for ConfigMap
#configMapGenerator:
#  - name: my-app-config
#    literals:
#      - ENV=production
#      - LOG_LEVEL=info

# Patch the deployment to override image
#images:
#  - name: myrepo/myapp
#    newTag: v1.2.3  # This can be overridden dynamically

