apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 980694407648.dkr.ecr.eu-west-3.amazonaws.com/testing/nginx:1.0
        name: contendor-nginx
        ports:
        - name: http
          containerPort: 80
